Tier 2:
    Adamantite
    Carmot
    Celestium
    Durasteel
    Hallowed
    Kyber
    Metallurgium
    Mythril
    Orichalcum
    Osmium
    Palladium
    Platinum
    Prometheum
    Runite
    Star Platinum
    Stormyx
